{
  "version": 2,
  "updates": [
    {
      "assignees": [ "Ocramius" ],
      "directory": "/",
      "package-ecosystem": "composer",
      "schedule": {
        "interval": "daily"
      },
      "versioning-strategy": "increase"
    },
    {
      "assignees": [ "Ocramius" ],
      "directory": "/",
      "package-ecosystem": "github-actions",
      "schedule": {
        "interval": "daily"
      }
    }
  ]
}
