language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: 5.3.3

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - time php -n ./vendor/bin/athletic -p ./tests/LazyMapPerformance/ -b ./tests/Bootstrap.php -f GroupedFormatter
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

after_script:
  - php vendor/bin/coveralls -v
